# Generated by Django 2.1.5 on 2019-01-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('interest_rate', models.FloatField(default=0.0)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('payment_period', models.DurationField(blank=True, default=0)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanBenefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laon_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('requiremets', models.CharField(max_length=200)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
