# Generated by Django 2.1.5 on 2019-01-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_company',
            name='how_to',
            field=models.TextField(default='How to apply', max_length=1000),
        ),
    ]
