# Generated by Django 2.1.5 on 2019-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_company_how_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_company',
            name='merits',
            field=models.TextField(default='Why apply for this loan', max_length=1000),
        ),
    ]
