# Generated by Django 2.1.5 on 2019-01-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_company_merits'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_company',
            name='requirements',
            field=models.TextField(default='Requirements', max_length=1000),
        ),
        migrations.AddField(
            model_name='loan_company',
            name='website',
            field=models.TextField(default='www', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan_company',
            name='interest_rate',
            field=models.TextField(default='Varies with the loan applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan_company',
            name='phone',
            field=models.TextField(blank=True, default=0),
        ),
    ]
