# Generated by Django 2.1.5 on 2019-01-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20190127_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_company',
            name='interest_rate',
            field=models.CharField(default='Varies with the loan applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='loan_company',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=50),
        ),
    ]
